package tokenexchange

import (
	"github.com/hashicorp/vault/sdk/framework"
	"github.com/hashicorp/vault/sdk/logical"
)

// pathJWKS returns the path configuration for /jwks endpoint
func pathJWKS(b *Backend) *framework.Path {
	return &framework.Path{
		Pattern: "jwks/?$",

		Fields: map[string]*framework.FieldSchema{
			"kid": {
				Type:        framework.TypeString,
				Description: "Optional: Filter by specific key ID",
				Query:       true,
			},
		},

		Operations: map[logical.Operation]framework.OperationHandler{
			logical.ReadOperation: &framework.PathOperation{
				Callback:                    b.pathJWKSRead,
				Summary:                     "Get JSON Web Key Set (JWKS) for token verification",
				ForwardPerformanceStandby:   true,
				ForwardPerformanceSecondary: true,
			},
		},

		HelpSynopsis:    "Retrieve public keys for JWT verification",
		HelpDescription: "Returns a JWKS (JSON Web Key Set) containing public keys for verifying tokens generated by this plugin. This endpoint is publicly accessible (unauthenticated) to allow external services to verify JWT signatures. Supports optional 'kid' query parameter to filter by key ID.",
	}
}
