---
apiVersion: v1
kind: Namespace
metadata:
  name: app

---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: demo-vault-connection
  namespace: app
spec:
  address: "http://10.10.0.30:8200"

---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: app
  name: demo-static-app

---
apiVersion: v1
kind: Secret
metadata:
  namespace: app
  name: demo-static-app-token
  annotations:
    kubernetes.io/service-account.name: demo-static-app
type: kubernetes.io/service-account-token

---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: static-auth
  namespace: app
spec:
  vaultConnectionRef: demo-vault-connection
  method: kubernetes
  mount: demo-auth-mount
  kubernetes:
    role: role1
    serviceAccount: demo-static-app

---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: demo-static-secret
  namespace: app
spec:
  vaultAuthRef: static-auth
  mount: secret
  type: kv-v2
  path: demo/config
  destination:
    create: true
    name: demo-secret
  refreshAfter: 30s
  rolloutRestartTargets:
    - kind: Deployment
      name: demo-app